POST  http://localhost:63075/checkcode/pic
Content-Type: application/json

{}

###
GET http://localhost:63010/content/course/40
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJiaXJ0aGRheVwiOlwiMjAyMi0wOS0yOFQxOToyODo0NlwiLFwiY3JlYXRlVGltZVwiOlwiMjAyMi0wOS0yOFQwODozMjowM1wiLFwiaWRcIjpcIjUwXCIsXCJuYW1lXCI6XCLlrabnlJ8xXCIsXCJuaWNrbmFtZVwiOlwi5aSn5rC054mbXCIsXCJzZXhcIjpcIjFcIixcInN0YXR1c1wiOlwiMVwiLFwidXNlcm5hbWVcIjpcInN0dTFcIixcInVzZXJwaWNcIjpcImh0dHA6Ly9maWxlLnh1ZWNoZW5nLXBsdXMuY29tL2RkZGZcIixcInV0eXBlXCI6XCIxMDEwMDFcIn0iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNjc4OTAzMjI1LCJhdXRob3JpdGllcyI6WyJ0ZXN0Il0sImp0aSI6IjEzZWNmOTMzLTY4ZWEtNGFkOS1iY2M0LWFhMDE3N2ZiYWZmYSIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.mPuc3lWJisZoDpIGeJle2AD6FyHXC9MlD54VftNJ_8M

###
POST http://localhost:63075/checkcode/verify?key=checkcode:41dad60b65b040e797e41d56a85f4e73&code=DD0G


###
POST http://localhost:63070/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJiaXJ0aGRheVwiOlwiMjAyMi0wOS0yOFQxOToyODo0NlwiLFwiY3JlYXRlVGltZVwiOlwiMjAyMi0wOS0yOFQwODozMjowM1wiLFwiaWRcIjpcIjUwXCIsXCJuYW1lXCI6XCLlrabnlJ8xXCIsXCJuaWNrbmFtZVwiOlwi5aSn5rC054mbXCIsXCJzZXhcIjpcIjFcIixcInN0YXR1c1wiOlwiMVwiLFwidXNlcm5hbWVcIjpcInN0dTFcIixcInVzZXJwaWNcIjpcImh0dHA6Ly9maWxlLnh1ZWNoZW5nLXBsdXMuY29tL2RkZGZcIixcInV0eXBlXCI6XCIxMDEwMDFcIn0iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNjc4OTAzMjI1LCJhdXRob3JpdGllcyI6WyJ0ZXN0Il0sImp0aSI6IjEzZWNmOTMzLTY4ZWEtNGFkOS1iY2M0LWFhMDE3N2ZiYWZmYSIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.mPuc3lWJisZoDpIGeJle2AD6FyHXC9MlD54VftNJ_8M
Content-Type: application/json

{}

###
POST http://localhost:63070/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username=zhangsan&password=123
Accept: application/json

###
POST http://localhost:63070/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username={"username":"stu1","authType":"password", "password": "111111"}